FROM node:bookworm
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
#https://nextjs.org/telemetry
ENV NEXT_TELEMETRY_DISABLED=1 
CMD ["npm", "run", "dev"]


# From the nextjs docker example https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
# USER nextjs
#
# EXPOSE 3000
#
# ENV PORT=3000
#
# # server.js is created by next build from the standalone output
# # https://nextjs.org/docs/pages/api-reference/next-config-js/output
# ENV HOSTNAME="0.0.0.0"
# CMD ["node", "server.js"]
