# Use the official Ruby image
FROM ruby:bookworm

# Set the working directory
WORKDIR /app

# Install nano editor and any necessary dependencies
RUN apt-get update && apt-get install -y nano

# Copy Gemfile and Gemfile.lock for dependency installation
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the rest of the application code
COPY . .

# Command to start the Rails server and remove any existing PID file
CMD ["sh", "-c", "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"]
